export type Lang = "en" | "es";

export const copy = {
  en: {
    nav: {
      home: "Home",
      gallery: "Gallery",
      location: "Location",
      contact: "Contact",
    },
    lang: { en: "EN", es: "ES", switch: "Language" },
    hero: {
      kicker: "Kissimmee, Florida",
      line1: "Where there is quality,",
      line2: "there is no competition.",
      sub: "OEM originals and precision replicas. A family shop run by women — fitment, financing, and shipping to every state.",
      cta: "View the gallery",
      ctaSecondary: "Call the shop",
      scroll: "Scroll",
    },
    status: {
      open: "Open now",
      closed: "Closed",
      weekend: "Closed Sunday",
      until: "until",
      opens: "Opens",
    },
    marquee: [
      "OEM originals",
      "Replica wheels",
      "Nationwide shipping",
      "In-store financing",
      "Fitment help",
      "Family owned",
    ],
    services: {
      kicker: "01 — Offerings",
      title: "Wheels that actually fit.",
      lead: "From factory-correct replacements to statement replicas. We lock the spec, then you take the set — or we ship it. Need them mounted? We work with people who install.",
      items: [
        {
          title: "OEM originals",
          body: "Factory-correct rims when you want the real piece — replacements, upgrades, and hard-to-find sizes.",
        },
        {
          title: "Replica wheels",
          body: "Clean replica designs that hold a look without the collector price. Gloss, machined, and chrome finishes.",
        },
        {
          title: "Fitment & installer partners",
          body: "Bolt pattern, offset, and load rating checked before anything leaves the shop. We don't mount rims in-house — we work with trusted local installers who do.",
        },
        {
          title: "Ship the set",
          body: "We pack and ship wheels to every state. Call with year, make, model — we will confirm the spec.",
        },
      ],
    },
    about: {
      kicker: "02 — The shop",
      title: "A family business, run by women.",
      body: "Obsessions Wheels LLC specializes in original rims and replicas of the original. We are a family shop in Kissimmee — bilingual, straightforward, and particular about fitment. Walk in, send a photo, or call. We will tell you what actually bolts on.",
      points: [
        "Bilingual staff — English and Spanish",
        "Open Monday through Saturday",
        "Financing through Snap, AFF, and Koalafi",
        "Cash App accepted",
      ],
    },
    gallery: {
      kicker: "03 — Work",
      title: "On the rack and on the street.",
      cta: "Open full gallery",
      close: "Close",
      prev: "Previous",
      next: "Next",
    },
    financing: {
      kicker: "04 — Pay over time",
      title: "Financing, if you need it.",
      lead: "Apply with a partner below or ask in the shop. Approval is between you and the lender — we will walk you through it.",
      apply: "Apply",
      instore: "Ask in store",
      partners: [
        {
          id: "snap",
          name: "Snap Finance",
          href: "https://apply.snapfinance.com/snap-com/landing?paramId=xNur%2BAldYGGc%2FMeZGkj0FD3uVgvnqTCz&source=INTERNET",
          logo: "/brand/snap.png",
        },
        {
          id: "aff",
          name: "American First Finance",
          href: "https://americanfirstfinance.com/app/?dealer=23447&loc=1&src=UA&usetextpin=Y",
          logo: "/brand/american.png",
        },
        {
          id: "koalafi",
          name: "Koalafi",
          href: "https://www.koalafi.com/",
          logo: "/brand/koalafi.png",
        },
      ],
    },
    faq: {
      kicker: "05 — Questions",
      title: "Before you drive over.",
      items: [
        {
          q: "Do you install wheels?",
          a: "We don't mount them here. We confirm fitment, sell the set, and work with people who install — we can point you to a trusted shop in the area.",
        },
        {
          q: "How do I know a wheel will fit?",
          a: "Bring the year, make, model, and current size — or a photo of the door sticker. We confirm bolt pattern, offset, and center bore before you pay.",
        },
        {
          q: "OEM or replica — what's the difference?",
          a: "OEM is the factory piece (or a genuine original). Replicas match a look at a different price. We stock and source both.",
        },
        {
          q: "Do you ship outside Florida?",
          a: "Yes. We ship wheel sets anywhere in the United States.",
        },
        {
          q: "What payment methods do you take?",
          a: "Card, cash, Cash App, and financing through Snap, American First Finance, and Koalafi.",
        },
      ],
    },
    visit: {
      kicker: "Hours",
      title: "Come by the shop.",
      days: [
        { label: "Monday", value: "10:00 AM – 5:30 PM" },
        { label: "Tuesday", value: "10:00 AM – 5:30 PM" },
        { label: "Wednesday", value: "10:00 AM – 5:30 PM" },
        { label: "Thursday", value: "10:00 AM – 5:30 PM" },
        { label: "Friday", value: "10:00 AM – 5:30 PM" },
        { label: "Saturday", value: "10:00 AM – 5:30 PM" },
        { label: "Sunday", value: "Closed" },
      ],
      directions: "Get directions",
      office: "Office",
      cell: "Cell / WhatsApp",
    },
    contact: {
      kicker: "Write us",
      title: "Tell us the car. We'll tell you the wheel.",
      lead: "Fitment questions, a set you saw on Instagram, or a shipping quote — send it here. We answer from the shop during hours.",
      name: "Name",
      email: "Email",
      phone: "Phone",
      message: "Message",
      namePh: "Full name",
      emailPh: "you@email.com",
      phonePh: "Mobile number",
      messagePh: "Year, make, model, and what you need.",
      submit: "Send message",
      sending: "Sending…",
      success: "Message sent. We'll get back to you from the shop.",
      error: "Could not send. Call or WhatsApp us instead.",
      required: "This field is required.",
    },
    footer: {
      blurb:
        "Obsessions Wheels LLC specializes in original rims and replicas of the original. A family business run by women.",
      contacts: "Contacts",
      social: "Social",
      socialLead: "Let's get connected. Stay updated on what we are doing in the shop.",
      privacy: "Privacy",
      terms: "Terms",
      rights: "All rights reserved.",
    },
    mobile: {
      call: "Call",
      chat: "WhatsApp",
      map: "Map",
    },
    socials: {
      kicker: "Our socials",
      title: "Let's get connected.",
      lead: "Stay updated on all that we are doing in the shop.",
    },
    pages: {
      galleryTitle: "Gallery",
      galleryLead: "A slice of what moves through the shop.",
      locationTitle: "Location & hours",
      locationLead: "1897 John Henry Jones Blvd, Kissimmee — just off the everyday drive.",
      contactTitle: "Contact",
      privacyTitle: "Privacy",
      termsTitle: "Terms",
    },
    notFound: {
      title: "This page is not on the rack.",
      body: "The link is missing or outdated.",
      home: "Back home",
    },
  },
  es: {
    nav: {
      home: "Inicio",
      gallery: "Galería",
      location: "Ubicación",
      contact: "Contacto",
    },
    lang: { en: "EN", es: "ES", switch: "Idioma" },
    hero: {
      kicker: "Kissimmee, Florida",
      line1: "Donde hay calidad,",
      line2: "no hay competencia.",
      sub: "Aros originales OEM y réplicas precisas. Un negocio familiar dirigido por mujeres — medida, financiamiento y envíos a todo el país.",
      cta: "Ver la galería",
      ctaSecondary: "Llamar a la tienda",
      scroll: "Bajar",
    },
    status: {
      open: "Abierto ahora",
      closed: "Cerrado",
      weekend: "Cerrado el domingo",
      until: "hasta",
      opens: "Abre",
    },
    marquee: [
      "Originales OEM",
      "Aros réplica",
      "Envíos a todo EE. UU.",
      "Financiamiento",
      "Asesoría de medida",
      "Negocio familiar",
    ],
    services: {
      kicker: "01 — Oferta",
      title: "Aros que sí calzan.",
      lead: "Desde reemplazos de fábrica hasta réplicas que se notan. Confirmamos la medida y te los entregamos o te los enviamos. ¿Hay que montarlos? Trabajamos con gente que instala.",
      items: [
        {
          title: "Originales OEM",
          body: "Aros de fábrica cuando quieres la pieza real — reemplazos, mejoras y tallas difíciles.",
        },
        {
          title: "Aros réplica",
          body: "Diseños limpios que sostienen el look sin precio de coleccionista. Brillo, maquinado y cromo.",
        },
        {
          title: "Medida e instaladores",
          body: "Patrón de birlos, offset y carga se revisan antes de salir. No montamos aros en la tienda — trabajamos con instaladores de confianza que sí lo hacen.",
        },
        {
          title: "Enviamos el juego",
          body: "Empacamos y enviamos aros a todos los estados. Llama con año, marca y modelo.",
        },
      ],
    },
    about: {
      kicker: "02 — La tienda",
      title: "Un negocio familiar, dirigido por mujeres.",
      body: "Obsessions Wheels LLC se especializa en aros originales y réplicas del original. Somos un taller familiar en Kissimmee — bilingüe, directo y exigente con la medida. Entra, manda una foto o llama. Te decimos lo que sí calza.",
      points: [
        "Personal bilingüe — inglés y español",
        "Abierto de lunes a sábado",
        "Financiamiento con Snap, AFF y Koalafi",
        "Se acepta Cash App",
      ],
    },
    gallery: {
      kicker: "03 — Trabajo",
      title: "En el rack y en la calle.",
      cta: "Ver galería completa",
      close: "Cerrar",
      prev: "Anterior",
      next: "Siguiente",
    },
    financing: {
      kicker: "04 — Paga en cuotas",
      title: "Financiamiento, si lo necesitas.",
      lead: "Aplica con un socio o pregunta en la tienda. La aprobación es entre tú y el prestamista — te guiamos.",
      apply: "Aplicar",
      instore: "Pregunta en tienda",
      partners: [
        {
          id: "snap",
          name: "Snap Finance",
          href: "https://apply.snapfinance.com/snap-com/landing?paramId=xNur%2BAldYGGc%2FMeZGkj0FD3uVgvnqTCz&source=INTERNET",
          logo: "/brand/snap.png",
        },
        {
          id: "aff",
          name: "American First Finance",
          href: "https://americanfirstfinance.com/app/?dealer=23447&loc=1&src=UA&usetextpin=Y",
          logo: "/brand/american.png",
        },
        {
          id: "koalafi",
          name: "Koalafi",
          href: "https://www.koalafi.com/",
          logo: "/brand/koalafi.png",
        },
      ],
    },
    faq: {
      kicker: "05 — Preguntas",
      title: "Antes de venir.",
      items: [
        {
          q: "¿Instalan los aros?",
          a: "No los montamos aquí. Confirmamos la medida, vendemos el juego y trabajamos con gente que instala — te podemos recomendar un taller de confianza.",
        },
        {
          q: "¿Cómo sé que el aro va a calzar?",
          a: "Trae año, marca, modelo y talla actual — o una foto de la etiqueta de la puerta. Confirmamos birlos, offset y centro antes de cobrar.",
        },
        {
          q: "OEM o réplica — ¿cuál es la diferencia?",
          a: "OEM es la pieza de fábrica (o un original genuino). Las réplicas copian el look a otro precio. Trabajamos las dos.",
        },
        {
          q: "¿Envían fuera de Florida?",
          a: "Sí. Enviamos juegos de aros a cualquier estado de EE. UU.",
        },
        {
          q: "¿Qué formas de pago aceptan?",
          a: "Tarjeta, efectivo, Cash App y financiamiento con Snap, American First Finance y Koalafi.",
        },
      ],
    },
    visit: {
      kicker: "Horario",
      title: "Pasa por la tienda.",
      days: [
        { label: "Lunes", value: "10:00 AM – 5:30 PM" },
        { label: "Martes", value: "10:00 AM – 5:30 PM" },
        { label: "Miércoles", value: "10:00 AM – 5:30 PM" },
        { label: "Jueves", value: "10:00 AM – 5:30 PM" },
        { label: "Viernes", value: "10:00 AM – 5:30 PM" },
        { label: "Sábado", value: "10:00 AM – 5:30 PM" },
        { label: "Domingo", value: "Cerrado" },
      ],
      directions: "Cómo llegar",
      office: "Oficina",
      cell: "Celular / WhatsApp",
    },
    contact: {
      kicker: "Escríbenos",
      title: "Dinos el carro. Te decimos el aro.",
      lead: "Dudas de medida, un juego que viste en Instagram o una cotización de envío — mándalo aquí. Contestamos desde la tienda en horario.",
      name: "Nombre",
      email: "Correo",
      phone: "Teléfono",
      message: "Mensaje",
      namePh: "Nombre completo",
      emailPh: "tucorreo@email.com",
      phonePh: "Número celular",
      messagePh: "Año, marca, modelo y lo que necesitas.",
      submit: "Enviar mensaje",
      sending: "Enviando…",
      success: "Mensaje enviado. Te respondemos desde la tienda.",
      error: "No se pudo enviar. Llámanos o escribe por WhatsApp.",
      required: "Este campo es obligatorio.",
    },
    footer: {
      blurb:
        "Obsessions Wheels LLC se especializa en aros originales y réplicas del original. Un negocio familiar dirigido por mujeres.",
      contacts: "Contactos",
      social: "Redes",
      socialLead: "Conéctate. Mira lo que estamos haciendo en la tienda.",
      privacy: "Privacidad",
      terms: "Términos",
      rights: "Todos los derechos reservados.",
    },
    mobile: {
      call: "Llamar",
      chat: "WhatsApp",
      map: "Mapa",
    },
    socials: {
      kicker: "Nuestras redes",
      title: "Conéctate con nosotros.",
      lead: "Mantente al día con todo lo que hacemos en la tienda.",
    },
    pages: {
      galleryTitle: "Galería",
      galleryLead: "Una muestra de lo que pasa por la tienda.",
      locationTitle: "Ubicación y horario",
      locationLead: "1897 John Henry Jones Blvd, Kissimmee.",
      contactTitle: "Contacto",
      privacyTitle: "Privacidad",
      termsTitle: "Términos",
    },
    notFound: {
      title: "Esta página no está en el rack.",
      body: "El enlace no existe o ya no sirve.",
      home: "Volver al inicio",
    },
  },
} as const;

export type Copy = (typeof copy)[Lang];
