backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/"
logo_url: "https://i.ibb.co/pK9xg53/Untitled-design.png"
public_folder: "/assets/"
collections:
  - name: "page"
    label: "Pagina"
    folder: "src/pages"
    description: >
      Paginas de sitio web. Se pueden crear paginas para cada una de las secciones de la web.
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "layout",
          name: "layout",
          widget: "text",
          default: "pages.njk",
        }

  - name: "faq"
    label: "Frequently Asked Questions"
    description: >
      Preguntas frecuentes.
    folder: "src/frequentlyaskedquestions"
    slug: "{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Question", name: "title", widget: "string" }
      - { label: "Response", name: "response", widget: "string" }

  - name: "popup"
    label: "Popup"
    folder: "src/popup"
    slug: "{{slug}}"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Response", name: "response", widget: "string" }

  - name: "services"
    label: "Services"
    description: >
      Servicios que ofrecemos. Esto es para la parte de servicios en la pagina inicial.
    folder: "src/services"
    slug: "{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Service", name: "service", widget: "string" }

  - name: "footer"
    label: "Footer"
    editor:
      preview: false
    description: >
      Esto es la parte de abajo de la pagina web.
    folder: "src/footer"
    slug: "{{slug}}"
    create: false
    fields:
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Office Number", name: "officenumber", widget: "string" }
      - { label: "Cellular Number", name: "cellularnumber", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Address Link", name: "addresslink", widget: "string" }